### ISSUE TITLE
Add ability to load an existing cron expression and render it 

### ISSUE THREAD

**Issue by LBoraz** [rvalenciano/ngx-cron-jobs-orig#20]
the component will create the correct cron expression but it's able to display an already generated one.
Say you have this expression:

0 15 * * * ?

and bind that value to the component with ngModel, the component will display a blank dropdown.
Basically one can only create new expressions and not display previously created ones

**Comment by rvalenciano** [comment]
So @LBoraz you're talking about reversing the process? You put an already existing cron extension and you want to fill the dropdown according to it?

**Comment by LBoraz** [comment]
yes, i'd like to provide an already existing expression (generated with the component) through ngModel. 
In my case i have a form that allows to configure schedules (one attribute of the schedule is the cron expr), and the second time (when the schedule has already been and someone wants to edit it) it would be nice to get the dropdowns set correctly so that the user can read back the expression he saved (in a non-techy format).

**Comment by LBoraz** [comment]
if you tell me what place in the code would need to be changed to support this, i can probably find the time to do the change myself and submit a pull request.

**Comment by sudhakar-sekar** [comment]
@LBoraz 
Please use [validate]="true" to load on existing CRON expression.

**Comment by rvalenciano** [comment]
Will close issue, new repo project can be found https://github.com/yp2/ngx-cron-jobs
