### ISSUE TITLE
Unable to install in Angular 7 App

### ISSUE THREAD

**Issue by skinman55** [rvalenciano/ngx-cron-jobs-orig#22]
Getting this error after installing the package in an app running Angular 7.1.3

ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-cron-jobs/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

**Comment by Araknos** [comment]
Same problem for Angular 7:
```
ERROR in ./node_modules/ngx-cron-jobs/ngx-cron-jobs.es5.js 37:9
Module parse failed: Identifier '__extends' has already been declared (37:9)
You may need an appropriate loader to handle this file type.
|     return extendStatics(d, b);
| };
> function __extends(d, b) {
|     extendStatics(d, b);
|     function __() { this.constructor = d; }
```

**Comment by bbahaida** [comment]
Same problem also for Angular 7 :

Module parse failed: Identifier '__extends' has already been declared (37:9)
You may need an appropriate loader to handle this file type.
|     return extendStatics(d, b);
| };
> function __extends(d, b) {
|     extendStatics(d, b);
|     function __() { this.constructor = d; }

**Comment by bbahaida** [comment]
> Same problem also for Angular 7 :
> 
> `Module parse failed: Identifier '__extends' has already been declared (37:9) You may need an appropriate loader to handle this file type. | return extendStatics(d, b); | }; function __extends(d, b) { | extendStatics(d, b); | function __() { this.constructor = d; }`

I fixed it by deleting the file ngx-cron-jobs.es5.js

**Comment by rvalenciano** [comment]
Will close issue, new repo project can be found https://github.com/yp2/ngx-cron-jobs
