### ISSUE TITLE
ngx-cron-jobs forked repo

### ISSUE THREAD

**Issue by yp2** [rvalenciano/ngx-cron-jobs-orig#23]
Hi, I delete my fork. Create new repo ngx-cron-jobs. Now you can archive this repo or delete this. If new issue will be create in this repo, please redirect it to [yp2/ngx-cron-jobs](https://github.com/yp2/ngx-cron-jobs) repo.

**Comment by rvalenciano** [comment]
Will close issue, new repo project can be found https://github.com/yp2/ngx-cron-jobs
